%prefix "cap"
%auxil "struct cst_Root*"
%value "cst_index"

%header {
    #define PCC_AST_NODE_CUSTOM_DATA_DEFINED

    #include "src/ast/cst.h"
    #include "src/error.h"

    #include "src/grammar/helper.h"
}
%source {
    #include "src/ast/cst.c"
    #include "src/error.c"
}

_start <- n:expression { $$ = n; }

%import "grammar/whitespace.peg"
%import "grammar/atoms.peg"
%import "grammar/expression.peg"
